services:
  app:
    build: .
    container_name: potatoDBServer
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}
    command: pnpm run dev
