version: "3.8"

services:
  app:
    build: .
    container_name: potatoDBServer
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm run dev
