services:
  app:
    build: .
    container_name: potatoDBServer
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}
